export const user = {
    LOGIN: "LOGIN",
    REGISTER: "REGISTER",

    GET_LOGIN_USER: "GET_LOGIN_USER",
    SET_LOGIN_USER: "SET_LOGIN_USER",

    GET_LINE_USER_INFO: "GET_LINE_USER_INFO",
    SET_LINE_USER_INFO: "SET_LINE_USER_INFO",
    FIND_LINE_USER_INFO: "FIND_LINE_USER_INFO",

    SEARCH_USER: "SEARCH_USER",
    GET_SEARCH_RESULT_LIST: "GET_SEARCH_RESULT_LIST"
}

export const chat = {
    LOAD_HIS_CHAT_RECORDS: "LOAD_HIS_CHAT_RECORDS",
    ADD_CHAT_RECORD: "ADD_CHAT_RECORD"
}