//查询权限列表
export const QUERY_LIST = "QUERY_LIST"

//查询权限关联资源列表
export const QUERY_PERMISSION_RESOURCE_LIST = "QUERY_PERMISSION_RESOURCE_LIST"

//设置编辑的权限数据
export const SET_EDIT_PERMISSION_DATA = "SET_EDIT_PERMISSION_DATA"

//获取编辑的权限数据
export const GET_EDIT_PERMISSION_DATA = "GET_EDIT_PERMISSION_DATA"

//保存权限
export const SAVE_EDIT_PERMISSION = "SAVE_EDIT_PERMISSION"

//设置分配的资源列表
export const SET_ASSIGNED_RESOURCES = "SET_ASSIGNED_RESOURCES"

//更新权限的资源列表
export const PUT_EDIT_PERMISSION_RESOURCES = "PUT_EDIT_PERMISSION_RESOURCES"

//保存分配的资源
export const SAVE_ASSIGNED_RESOURCES = "SAVE_ASSIGNED_RESOURCES"

//删除权限
export const DELETE_PERMISSIONS = "DELETE_PERMISSIONS"