server:
  port: 7005

spring:
  application:
    name: account-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    host: 192.168.0.45
    db: my_project_account
    url: jdbc:mysql://${spring.datasource.host}:3306/${spring.datasource.db}?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0 # 0到1之间，1表示全部采样

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

feign:
  hystrix:
    enabled: true