export const GET_LOGIN_USER = "GET_LOGIN_USER";
export const SAVE_LOGIN_USER = "SAVE_LOGIN_USER";
export const LOGIN_BY_PHONE_CODE = "LOGIN_BY_PHONE_CODE";
export const LOGIN_BY_ACCOUNT = "LOGIN_BY_ACCOUNT";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";