eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
server:
  port: 7002

spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  cache:
    ehcache:
      config: classpath:cache/ehcache.xml
    type: ehcache
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0 # 0到1之间，1表示全部采样
#      routes:
#        - id: file-server
#          uri: lb://file-server
#          predicates:
#            - Path=/filer-server/**
#          filters:
#            - StripPrefix=1 # 去除请求地址中的filer-server
#        - id: account-server
#          uri: lb://account-server
#          predicates:
#            - Path=/predicates/**


feign:
  hystrix:
    enabled: true