
export const mutations = {
    SET_SELECTED_KEYS: "SET_SELECTED_KEYS",
    SET_ROLE_LIST: "SET_ROLE_LIST",
    SET_ASSIGN_ROLE_USER: "SET_ASSIGN_ROLE_USER"
}

export const actions = {
    SELECT_PAGE: "SELECT_PAGE",
    BATCH_DELETE: "BATCH_DELETE",
    ASSIGN_USER_ROLES: "ASSIGN_USER_ROLES"
}

export const getters = {
    GET_USER_ASSIGNED_INFO: "GET_USER_ASSIGNED_INFO"
}
